name: CI

on:
  push:
    paths:
      - "crisAtelie/**"
      - ".github/workflows/front.yml"
  pull_request:
    paths:
      - "crisAtelie/**"
      - ".github/workflows/front.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        working-directory: crisAtelie
        run: |
          yarn install
